### ISSUE TITLE
Android - Conflict with ti.map 2.3.10 module jars on Ti SDK 5.5.1.GA

### ISSUE THREAD

**Issue by ygbr** [pinio/tiads#1]
When trying to use this module together with ti.map on Titanium 5.5.1.GA we get a lot of conflicts.

Titanium SDK: **5.5.1.GA**
ti.map module: **2.3.10**
tiads module: **1.0.0**

If we remove the **google-play-services-base.jar** from the **ti.map** module lib directory, the tiads module runs fine and works properly but the maps cause the following crash when instanced:

```
[DEBUG] AndroidRuntime: Shutting down VM
[ERROR] TiApplication: (main) [358,27220] Sending event: exception on thread: main msg:java.lang.NoSuchMethodError: No static method zzbY(Ljava/lang/String;)V in class Lcom/google/android/gms/common/internal/zzu; or its super classes (declaration of 'com.google.android.gms.common.internal.zzu' appears in /data/app/br.com.pinion-1/base.apk); Titanium 5.5.1,2016/09/27 05:39,b18727f
[ERROR] TiApplication: java.lang.NoSuchMethodError: No static method zzbY(Ljava/lang/String;)V in class Lcom/google/android/gms/common/internal/zzu; or its super classes (declaration of 'com.google.android.gms.common.internal.zzu' appears in /data/app/br.com.pinion-1/base.apk)
[ERROR] TiApplication: 	at com.google.android.gms.maps.SupportMapFragment.getMapAsync(Unknown Source)
[ERROR] TiApplication: 	at ti.map.TiUIMapView.createFragment(TiUIMapView.java:112)
[ERROR] TiApplication: 	at org.appcelerator.titanium.view.TiUIFragment.<init>(TiUIFragment.java:50)
[ERROR] TiApplication: 	at ti.map.TiUIMapView.<init>(TiUIMapView.java:69)
[ERROR] TiApplication: 	at ti.map.ViewProxy.createView(ViewProxy.java:80)
[ERROR] TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:493)
[ERROR] TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:479)
[ERROR] TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:517)
[ERROR] TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:501)
[ERROR] TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:479)
[ERROR] TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleAdd(TiViewProxy.java:680)
[ERROR] TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.add(TiViewProxy.java:574)
[ERROR] TiApplication: 	at ti.modules.titanium.ui.WindowProxy.windowCreated(WindowProxy.java:263)
[ERROR] TiApplication: 	at org.appcelerator.titanium.TiActivityWindows.windowCreated(TiActivityWindows.java:33)
[ERROR] TiApplication: 	at org.appcelerator.titanium.TiBaseActivity.windowCreated(TiBaseActivity.java:559)
[ERROR] TiApplication: 	at org.appcelerator.titanium.TiBaseActivity.onCreate(TiBaseActivity.java:673)
[ERROR] TiApplication: 	at org.appcelerator.titanium.TiActivity.onCreate(TiActivity.java:18)
[ERROR] TiApplication: 	at android.app.Activity.performCreate(Activity.java:6904)
[ERROR] TiApplication: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
[ERROR] TiApplication: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266)
[ERROR] TiApplication: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
[ERROR] TiApplication: 	at android.app.ActivityThread.access$1100(ActivityThread.java:229)
[ERROR] TiApplication: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
[ERROR] TiApplication: 	at android.os.Handler.dispatchMessage(Handler.java:102)
[ERROR] TiApplication: 	at android.os.Looper.loop(Looper.java:148)
[ERROR] TiApplication: 	at android.app.ActivityThread.main(ActivityThread.java:7325)
[ERROR] TiApplication: 	at java.lang.reflect.Method.invoke(Native Method)
[ERROR] TiApplication: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
[ERROR] TiApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
[DEBUG] HTTPClient: The persistent handle is disposed.
[ERROR] AndroidRuntime: FATAL EXCEPTION: main
[ERROR] AndroidRuntime: Process: br.com.pinion, PID: 18105
[ERROR] AndroidRuntime: java.lang.NoSuchMethodError: No static method zzbY(Ljava/lang/String;)V in class Lcom/google/android/gms/common/internal/zzu; or its super classes (declaration of 'com.google.android.gms.common.internal.zzu' appears in /data/app/br.com.pinion-1/base.apk)
[ERROR] AndroidRuntime: 	at com.google.android.gms.maps.SupportMapFragment.getMapAsync(Unknown Source)
[ERROR] AndroidRuntime: 	at ti.map.TiUIMapView.createFragment(TiUIMapView.java:112)
[ERROR] AndroidRuntime: 	at org.appcelerator.titanium.view.TiUIFragment.<init>(TiUIFragment.java:50)
[ERROR] AndroidRuntime: 	at ti.map.TiUIMapView.<init>(TiUIMapView.java:69)
[ERROR] AndroidRuntime: 	at ti.map.ViewProxy.createView(ViewProxy.java:80)
[ERROR] AndroidRuntime: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:493)
[ERROR] AndroidRuntime: 	at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:479)
[ERROR] AndroidRuntime: 	at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:517)
[ERROR] AndroidRuntime: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:501)
[ERROR] AndroidRuntime: 	at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:479)
[ERROR] AndroidRuntime: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleAdd(TiViewProxy.java:680)
[ERROR] AndroidRuntime: 	at org.appcelerator.titanium.proxy.TiViewProxy.add(TiViewProxy.java:574)
[ERROR] AndroidRuntime: 	at ti.modules.titanium.ui.WindowProxy.windowCreated(WindowProxy.java:263)
[ERROR] AndroidRuntime: 	at org.appcelerator.titanium.TiActivityWindows.windowCreated(TiActivityWindows.java:33)
[ERROR] AndroidRuntime: 	at org.appcelerator.titanium.TiBaseActivity.windowCreated(TiBaseActivity.java:559)
[ERROR] AndroidRuntime: 	at org.appcelerator.titanium.TiBaseActivity.onCreate(TiBaseActivity.java:673)
[ERROR] AndroidRuntime: 	at org.appcelerator.titanium.TiActivity.onCreate(TiActivity.java:18)
[ERROR] AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6904)
[ERROR] AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
[ERROR] AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266)
[ERROR] AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
[ERROR] AndroidRuntime: 	at android.app.ActivityThread.access$1100(ActivityThread.java:229)
[ERROR] AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
[ERROR] AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
[ERROR] AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
[ERROR] AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7325)
[ERROR] AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
[ERROR] AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
[ERROR] AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
[ERROR] E/android.os.Debug( 1575): ro.product_ship = true
[ERROR] E/android.os.Debug( 1575): ro.debug_level = 0x4f4c
[ERROR] E/android.os.Debug( 1575): sys.mobilecare.preload = false
[ERROR] D/NetworkController.MobileSignalController(0/2147483643)( 2387): onSignalStrengthsChanged signalStrength=SignalStrength: 14 99 -120 -160 -120 -1 -1 99 2147483647 2147483647 2147483647 -1 2147483647 0x4 gsm|lte level=4
[ERROR] D/NetworkController.MobileSignalController(0/2147483643)( 2387): getMobileIconGroup(): 0
[ERROR] D/NetworkController.MobileSignalController(0/2147483643)( 2387): updateZVVMobileIconGroup(): 0
[ERROR] D/NetworkController.MobileSignalController(0/2147483643)( 2387): onSignalStrengthsChanged signalStrength=SignalStrength: 14 99 -120 -160 -120 -1 -1 99 2147483647 2147483647 2147483647 -1 2147483647 0x4 gsm|lte level=4
[ERROR] D/NetworkController.MobileSignalController(0/2147483643)( 2387): getMobileIconGroup(): 0
[ERROR] D/NetworkController.MobileSignalController(0/2147483643)( 2387): updateZVVMobileIconGroup(): 0
[ERROR] D/[WeatherWidget(1220)]  WeatherService(14254): {[EC3334F14841398C8B464A72D0E61AB7C564889C89112557F2146D56794659083956C77974A4825103AB5C5D4AC85EDAA24236388AC138058106446B92A35777]}
[ERROR] D/[WeatherWidget(1220)]  (14254): {[3AE6950019B083611567B0F9442DB03EEFA9050249635C043F7E254E316C2550]}
[ERROR] D/[WeatherWidget(1220)]  (14254): {[3AE6950019B083611567B0F9442DB03E5DDA24A68DD8F41CDE99F0ED3FBCA79D6E3672D13C47BC5ED8EFB051B507BC359E0BBE33CAC4DD26F7E7BD0DE7A87253A9C3C650BA065FAD34DFAC014CA6063A]}
[ERROR] D/[WeatherWidget(1220)]  (14254): {[A1AF0F6A1A65A89C43D705938923D0FEFB71880C4E84718DA0A3E1F383E54FB24509E0FBB917D66D2978C513F7383D4A3053B01023BD027BD5C6B984AE327ACD26928C80A6F39EF6633B2B1BD6D405D1A03DAE0D8587362656A58DBCB4575D8CEF15524E42B4FEA236B8FA47B6515F10]}
[ERROR] D/[WeatherWidget(1220)]  (14254): {[15C09394A4E9AFE55A5C62F22AB3FC5902EB2A2150B6646A86F2B3102D669614]}
[ERROR] D/NetworkController.MobileSignalController(0/2147483643)( 2387): onSignalStrengthsChanged signalStrength=SignalStrength: 13 99 -120 -160 -120 -1 -1 99 2147483647 2147483647 2147483647 -1 2147483647 0x4 gsm|lte level=4
[ERROR] D/NetworkController.MobileSignalController(0/2147483643)( 2387): getMobileIconGroup(): 0
[ERROR] D/NetworkController.MobileSignalController(0/2147483643)( 2387): updateZVVMobileIconGroup(): 0
-- End application log -------------------------------------------------------
```

If we remove the **google-play-services-base.jar** from the **tiads** module lib directory, the app crashes when we try to call the getAdvertisingIdInfo method with the following:

```
[ERROR] Failed to run dexer:
[ERROR]
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzau;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzje;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzjf;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzjg;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzjh;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzjh$zza;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzji;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzji$zza;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzjj;
[ERROR]
[ERROR] UNEXPECTED TOP-LEVEL EXCEPTION:
[ERROR] java.lang.RuntimeException: Translation has been interrupted
[ERROR]         at com.android.dx.command.dexer.Main.processAllFiles(Main.java:608)
[ERROR]         at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
[ERROR]         at com.android.dx.command.dexer.Main.run(Main.java:277)
[ERROR]         at com.android.dx.command.dexer.Main.main(Main.java:245)
[ERROR]         at com.android.dx.command.Main.main(Main.java:106)
[ERROR] Caused by: java.lang.InterruptedException: Too many errors
[ERROR]         at com.android.dx.command.dexer.Main.processAllFiles(Main.java:600)
[ERROR]         ... 4 more
```

We are using the google-play-services-base.jar and google-play-services-ads.jar from the https://github.com/appcelerator-modules/ti.admob module which according to this commit https://github.com/appcelerator-modules/ti.admob/commit/c8a7cff6e94a46da758ce011a1798908daf53dc9 is using the Google Play Services to v9.6.1 (rev 33) jars.

The module is working **fine** with **Ti SDK 6.0.3.GA + ti.map 3.0.1** module with no conflicts whatsoever.

**Comment by ygbr** [comment]
I have managed to compile a version of ti.map based on the latest code (6.0.0+) for running on Ti 5.x (changing the manifest, ndk and tooling from the ti.map android 3.0.2 tree)
It runs fine and both the maps and tiads works normally on the first app run.
The problem is that just after you close the app for the first time, the first activity gets "stuck" on the next runs.

😞

**Comment by TerranceSon** [comment]
Hi! all, is there anyone ever try ti.map and edit timodule.xml to set value 
<meta-data android:name="com.google.android.gms.version" android:value="10298000"/>
Im using ti.map 3.1.1 and seem while calling the map App always crash. I need to force the map to use this because of other module require the google play service version 10298000 to set in app.
